{
  "version": "1.0.0",
  "title": "Deploy infected fashion pod and inject latency on application level",
  "description": "Pod deploy incl. Chaos Monkey for Spring Boot to inject latency",
  "tags": [
    "microservice",
    "kubernetes",
    "chaos-monkey-spring-boot"
  ],
  "steady-state-hypothesis": {
    "title": "Services are all available and healthy",
    "probes": [
    {
      "name": "api-gateway-must-still-respond",
      "provider": {
        "type": "http",
        "url": "http://gateway-HOSTPATTERN.chaos.codecentric.io/startpage",
        "timeout": [0.25, 0.50]
      },
      "tolerance": 200,
      "type": "probe"
    }
    ]
  },
  "method": [
  {
    "type": "probe",
    "name": "all-services-are-healthy",
    "tolerance": true,
    "provider": {
      "type": "python",
      "module": "chaosk8s.probes",
      "func": "all_microservices_healthy",
      "arguments": {
        "ns": "shoppingdemo"
      }
    }
  },
  {
    "type": "action",
    "name": "deploy_cm4sb_fashion_pod",
    "provider": {
      "type": "process",
      "path": "kubectl",
      "arguments":{
        "apply":"",
        "-f":"../cm4sb/cm4sb_fashion_configure_latency.yaml"
      }
    },
    "pauses": {
      "after": 5
    }
  },
  {
    "type": "probe",
    "name": "check-gateway-response",
    "provider": {
      "type": "process",
      "path": "ab",
      "timeout": 60,
      "arguments": {
        "-n": "500",
        "-c": "4",
        "-s": "1",
        "-g": "output.data",
        "-v": "3",
        "https://gateway-HOSTPATTERN.chaos.codecentric.io/startpage": ""
      }
    }
  }
  ],
  "rollbacks": [
  {
    "type": "action",
    "name": "delete_cm4sb_fashion_pod",
    "provider": {
      "type": "process",
      "path": "kubectl",
      "arguments":{
        "delete":"",
        "-f":"../cm4sb/cm4sb_fashion_configure_latency.yaml"
      }
    }
  }
  ]
}