version: '3.3'

services:
  chaostoolkit:
    image: mrbwilms/chaostoolkit
    tty: true

  chaoshub:
    image: chaostoolkit/chaoshub:0.1.2
    ports:
      - "8888:8080"
    tty: true

  gateway:
    image: gateway
    ports:
      - "8080:8080"

  fashion:
    image: bestseller-fashion
    ports:
      - 8090-8092:8082

  toys:
    image: bestseller-toys
    ports:
      - "8081:8081"

  hot-deals:
    image: hot-deals
    ports:
      - "8083:8083"

  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"

  jaeger-server:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775"
      - "6831:6831/udp"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"