server:
  port: 8083
spring:
  profiles:
    active: chaos-monkey
  application:
    name: hotdeals
  zipkin:
    base-url: http://host.docker.internal:42699/com.instana.plugin.jaeger.trace
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: chaosmonkey
chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      latency-active: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/