server:
  port: 8081


# Init Chaos Monkey for Spring Boot by profile
spring:
  profiles:
    active: chaos-monkey
  application:
    name: toys-bestseller
  zipkin:
    base-url: http://host.docker.internal:42699/com.instana.plugin.jaeger.trace
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

# Configure Chaos Monkey - enabled = false
chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      latency-active: false

# Spring Boot Actuator Endpoint Chaos Monkey for Spring Boot
management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: chaosmonkey
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

